name: content-api-v2

# This workflow is triggered on push to the 'content-web' directory of the  main branch of the repository
on:
  push:
    branches:
    - master
    paths:
    - 'content-api/**'

  # Configure workflow to also support triggering manually
  workflow_dispatch:

# Environment variables are defined so that they can be used throughout the job definitions.
env:
  imageRepository: 'content-api'
  resourceGroupName: 'fabmedical-507381'
  containerRegistryName: 'acr507381'
  containerRegistry: 'acr507381.azurecr.io'
  dockerfilePath: './content-api'
  tag: '${{ github.run_id  }}'

# Jobs define the actions that take place when code is pushed to the main branch
jobs:

  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ${{ env.containerRegistry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - 
      name: Build and push an image to container registry
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.dockerfilePath  }}
        file: '${{ env.dockerfilePath }}/Dockerfile'
        repository: ${{ env.imageRepository }}
        tags: ${{ env.tag }},v1
